# Generated by Django 5.0.2 on 2024-03-04 04:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_editorsprofile_tota_posts'),
        ('posts', '0005_post_viwes_of_this'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='editor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='my_post', to='accounts.editorsprofile'),
        ),
    ]
