# Generated by Django 5.0.2 on 2024-03-04 04:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_editors'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='editorsprofile',
            name='average_rating',
        ),
        migrations.RemoveField(
            model_name='editorsprofile',
            name='tota_posts',
        ),
    ]
