# Generated by Django 5.0.2 on 2024-03-04 04:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_remove_editorsprofile_average_rating_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='editorsprofile',
            name='tota_posts',
            field=models.IntegerField(default=0),
        ),
    ]
