# Generated by Django 5.0.2 on 2024-03-02 10:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_category_remove_post_rating_post_categroy_rating'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='writer',
        ),
    ]
