# Generated by Django 5.0.2 on 2024-03-02 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0003_remove_post_writer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='slug',
        ),
        migrations.AlterField(
            model_name='rating',
            name='rating',
            field=models.IntegerField(choices=[(0, '0 out of 4'), (1, '1 out of 4'), (2, '2 out of 4'), (3, '3 out of 4'), (4, '4 out of 4')]),
        ),
    ]
