# Generated by Django 5.0.2 on 2024-03-04 04:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0004_remove_post_slug_alter_rating_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='viwes_of_this',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
